# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13md6bTHESIAbCcRbXQoWnPNAie58rwHA
"""

from flask import Flask
app = Flask(__name__)

from flask import request, abort
from linebot import  LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, TextSendMessage, LocationSendMessage, TemplateSendMessage, MessageTemplateAction, URITemplateAction, CarouselTemplate, CarouselColumn, ImageCarouselTemplate, ImageCarouselColumn


import os
line_bot_api = LineBotApi(os.environ.get('Channel_Access_Token'))
handler = WebhookHandler(os.environ.get('Channel_Secret'))

@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']
    body = request.get_data(as_text=True)
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return 'OK'


@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    mtext = event.message.text
    if mtext == '@今天喝什麼':#@轉盤樣板
        sendCarousel(event)

    elif mtext == '@今天吃什麼':#@圖片轉盤
        sendImgCarousel(event)

def sendCarousel(event):  #轉盤樣板 喝啥
    try:
        message = TemplateSendMessage(
            alt_text='轉盤樣板',
            template=CarouselTemplate(
                columns=[
                    CarouselColumn(
                        thumbnail_image_url='https://www.chickpt.com.tw/compassion_img?img=%2Fphotos%2F20230505%2F2156533%2F1683284127.787851127786.jpg',
                        title='五桐號',
                        actions=[
                            MessageTemplateAction(
                                label='菜單',
                                text='第一個轉盤樣板'
                               # image_url='https://cdn.myfeel-tw.com/media/ivNZjwSI1lp82JeXI5BA56UFiZr9IZsXKbKQrhRU.jpg'
                            )
                        ]
                    ),
                   CarouselColumn(
                        thumbnail_image_url='https://i.imgur.com/4QfKuz1.png',
                        title='COCO',
                        actions=[
                            MessageTemplateAction(
                                label='菜單',
                                text='我們有賣披薩'
                            )
                        ]
                    ),
                    CarouselColumn(
                        thumbnail_image_url='https://i.imgur.com/4QfKuz1.png',
                        title='迷客夏',
                        actions=[
                            MessageTemplateAction(
                                label='菜單',
                                text='我們有賣披薩'
                            )
                        ]
                    ),
                    CarouselColumn(
                        thumbnail_image_url='https://i.imgur.com/4QfKuz1.png',
                        title='先自然',
                        actions=[
                            MessageTemplateAction(
                                label='菜單',
                                text='我們有賣披薩'
                            )
                        ]
                    ),
                    CarouselColumn(
                        thumbnail_image_url='https://i.imgur.com/4QfKuz1.png',
                        title='清心福全',
                        actions=[
                            MessageTemplateAction(
                                label='菜單',
                                text='我們有賣披薩'
                            )
                        ]
                    ),
                    CarouselColumn(
                        thumbnail_image_url='https://i.imgur.com/4QfKuz1.png',
                        title='得正',
                        actions=[
                            MessageTemplateAction(
                                label='菜單',
                                text='我們有賣披薩'
                            )
                        ]
                    )
                ]
            )
        )
        line_bot_api.reply_message(event.reply_token,message)
    except:
        line_bot_api.reply_message(event.reply_token,TextSendMessage(text='發生錯誤！'))

def sendImgCarousel(event):  #圖片轉盤
    try:
        message = TemplateSendMessage(
            alt_text='圖片轉盤樣板',
            template=ImageCarouselTemplate(
                columns=[
                    ImageCarouselColumn(
                        image_url='https://i.imgur.com/4QfKuz1.png',
                        action=MessageTemplateAction(
                            label='文字訊息',
                            text='我們有賣披薩'
                        )
                    ),
                    ImageCarouselColumn(
                        image_url='https://i.imgur.com/qaAdBkR.png',
                        action=URITemplateAction(
                            label='連結星巴克',
                            uri='https://www.starbucks.com.tw/home/index.jspx'
                        )
                    ),
                    ImageCarouselColumn(
                        image_url='https://i.imgur.com/Qg0rsSk.jpg',
                        action=MessageTemplateAction(
                            label='座標位置',
                            text='@星巴克位置'
                        )
                    )
                ]
            )
        )
        line_bot_api.reply_message(event.reply_token,message)
    except:
        line_bot_api.reply_message(event.reply_token,TextSendMessage(text='發生錯誤！'))

def sendLocation(event):
    try:
        message = LocationSendMessage(
            title='星巴克 景美門市', 
            address='116台北市文山區景興路185號1-2F', 
            latitude=24.99301856466003,
            longitude=121.54439425767183
        )
        line_bot_api.reply_message(event.reply_token, message)
    except:
        line_bot_api.reply_message(event.reply_token,TextSendMessage(text='發生錯誤！'))

if __name__ == '__main__':
    app.run()
